// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL7jQUKti8IIjXo8jn3F9rR3KeH7d24lA',
    appId: '1:1051002383483:web:6ae05bfa20d309d7b2c6de',
    messagingSenderId: '1051002383483',
    projectId: 'swe-newsletter',
    authDomain: 'swe-newsletter.firebaseapp.com',
    storageBucket: 'swe-newsletter.firebasestorage.app',
    measurementId: 'G-M3X9LHMBJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQc7JD2jN_mkitXCQDWBbJGA94FxE_BeQ',
    appId: '1:1051002383483:android:2fa305fdabb7414eb2c6de',
    messagingSenderId: '1051002383483',
    projectId: 'swe-newsletter',
    storageBucket: 'swe-newsletter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBUnkn3kShr_H5Eh0rtIQfeUdyVh3qboI',
    appId: '1:1051002383483:ios:20e96bf2ef7505f8b2c6de',
    messagingSenderId: '1051002383483',
    projectId: 'swe-newsletter',
    storageBucket: 'swe-newsletter.firebasestorage.app',
    iosBundleId: 'com.example.newNewsletter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBUnkn3kShr_H5Eh0rtIQfeUdyVh3qboI',
    appId: '1:1051002383483:ios:20e96bf2ef7505f8b2c6de',
    messagingSenderId: '1051002383483',
    projectId: 'swe-newsletter',
    storageBucket: 'swe-newsletter.firebasestorage.app',
    iosBundleId: 'com.example.newNewsletter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL7jQUKti8IIjXo8jn3F9rR3KeH7d24lA',
    appId: '1:1051002383483:web:b4018a5673c0214cb2c6de',
    messagingSenderId: '1051002383483',
    projectId: 'swe-newsletter',
    authDomain: 'swe-newsletter.firebaseapp.com',
    storageBucket: 'swe-newsletter.firebasestorage.app',
    measurementId: 'G-1EE6VGT3VG',
  );
}
